collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4968306
  brandStrength: 0.2241548
  lightness: 0.7240225
  brandColors:
    - '#0A1214'
    - '#4D74AD'
    - '#6CA4D7'
    - '#92C2F0'
    - '#36332A'
  rhythmicContrast: 0.4918425
typography_spectrum: 0.3111298
layout_spectrum: 1
name: Fionwines
